import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Often needed for directives like *ngIf, *ngFor
import { RouterOutlet } from '@angular/router'; // Needed if you use <router-outlet> in the template

@Component({
  selector: 'app-root', // How you use this component in HTML (e.g., <app-root></app-root>)
  standalone: true, // Marks this as a standalone component
  imports: [CommonModule, RouterOutlet], // Import any modules/directives this component needs directly
  templateUrl: './app.component.html', // Links to the HTML template file
  styleUrls: ['./app.component.scss'] // Links to the CSS styles file
})
export class AppComponent {
  title = 'finance2.5'; // A simple property, often generated by the CLI

  // You can add methods and other properties here for your component's logic
}
